server:
  port: 8090
spring:
  thymeleaf:
    cache: false
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:h2:mem:db_dev;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://127.0.0.1:3306/db_dev
#    username: root
#    password:
custom:
  fileDirPath: /usr/file