import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
// import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={inter.className}>
        <nav>
            <ul>
              <li><Link href="/">홈</Link></li>
              <li><Link href="/about">소개</Link></li>
              <li><Link href="/article">게시판</Link></li>
              <li><Link href="/member/login">로그인</Link></li>
            </ul>
        </nav>  
        {children}
      </body>
    </html>
  );
}
